Feat: Add Theming with config.yml
Appsilon/LogAnalyzer pull request #15
Opened 2024-11-22 11:58 UTC by DeepanshKhurana

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*

Closes #14 

**Note to reviewers:** This was changed before `brand.yml` came into the picture and works quite similarly. Still, since this is underway and has existing PRs in sequence (#17, #20), it would make sense to go forward with this and then, do a cleanup refactor to use brand.yml with minor changes, if necessary. Although, I don't see the need as of yet because the branding is not as widely present in this app, owing to its simplicity. But it can be something we decide in the future.

## Description
- Adds `config.yml` branding + Sass modifications to access it
- Adds notes to `README.md` for the same
- Adds minor fix to `onClick` in the app list and job list `reactable` tables

[Loom recording with demo](https://www.loom.com/share/3234c87911df43e1a1b1fc484eaa4d99?sid=e88feee1-60ef-41cd-8bf2-e0db1672f3f9)

## Definition of Done
- [x] The change is thoroughly documented.
- [x] The CI passes (`R CMD check`, linter, unit tests, spelling).
- [x] Any generated files have been updated (e.g. `.Rd` files with `roxygen2::roxygenise()`)

2025-02-11 14:36 UTC, jakubnowicki requested changes
Hey, this is a nice improvement  :+1: It needs a little bit more polishing; please check my comments.

2025-02-11 14:36 UTC, jakubnowicki commented on app/main.R
>  # nolint start: box_func_import_count_linter
Please remove nolint.

2025-02-11 14:36 UTC, jakubnowicki commented on app/main.R
> +    })
Instead of using renderUI, it could be simpler to just read and create the style outside of ui and server and than use it inside (something like the good old `global.R`).

2025-02-11 14:36 UTC, jakubnowicki commented on app/logic/general_utils.R
> +  config = get("branding")
Do we actually need a default here?

2025-02-11 14:36 UTC, jakubnowicki commented on app/logic/general_utils.R
> +generate_css_variables <- function(
Maybe it is a good moment to start adding unit tests? This function looks like an opportunity :)

2025-02-11 14:36 UTC, jakubnowicki commented on app/logic/empty_state_utils.R
> +  color = NULL
This is inconsistent, as `replace_svg_fill` will not accept `NULL`.

2025-02-11 14:36 UTC, jakubnowicki commented on config.yml
> +        primary: "#0099f9"
Maybe it would be good to move `primary` to the top?

2025-02-11 14:36 UTC, jakubnowicki commented on README.md
> +    - You can edit the branding in the `config.yml` file. You'll find the `colors` key which will build the CSS.
I suggest expanding this with some description of what particular colors do.

2025-04-13 11:54 UTC, DeepanshKhurana commented on app/main.R
>  # nolint start: box_func_import_count_linter
Done, I've removed all `nolint`s!

2025-04-13 11:54 UTC, DeepanshKhurana commented on app/main.R
> +    })
I think this was a great suggestion, saves us the extra reactive usage when none is required. I've moved the code to a section above the `ui()`

2025-04-13 11:54 UTC, DeepanshKhurana commented on app/logic/general_utils.R
> +  config = get("branding")
Correct. I've removed the default value.

2025-04-13 11:55 UTC, DeepanshKhurana commented on app/logic/general_utils.R
> +generate_css_variables <- function(
I've added tests for all the `general_utils` functions! :D

2025-04-13 11:55 UTC, DeepanshKhurana commented on app/logic/empty_state_utils.R
> +  color = NULL
Resolved!

2025-04-13 11:55 UTC, DeepanshKhurana commented on config.yml
> +        primary: "#0099f9"
Makes sense. I've moved it to the top!

2025-04-13 11:55 UTC, DeepanshKhurana commented on README.md
> +    - You can edit the branding in the `config.yml` file. You'll find the `colors` key which will build the CSS.
Yes! I've added a few points explaining how the colors work. It should at least indicate the user what colors affect what values.

2025-05-09 17:45 UTC, vituri reviewed
Looks good! Later we will be able to use the new brand.yml file. 

I see that all other comments by Jakub Nowicki were solved as well since his last review.

2025-05-09 17:45 UTC, vituri commented on tests/testthat/test-general_utils.R
> +})
Is there a chance that the message is something like the following?
```r
> check_text_error("No error found")
[1] TRUE
```
If yes, maybe to explicit that the string start with one of the wordlist is enough, like the following:

```r
check_text_error <- function(
    text,
    wordlist = c("halt", "err", "terminat", "not found"),
    ignore_case = TRUE
) {
  grepl(
    paste0("^", wordlist, collapse = "|"),
    text,
    ignore.case = ignore_case
  )
}

check_text_error("No error found")
check_text_error("Error: aaa")
```

2025-10-03 07:52 UTC, DeepanshKhurana commented on tests/testthat/test-general_utils.R
> +})
Great catch! I finally took a look at this and added your code. Thanks for the suggestion.

2025-10-03 08:12 UTC, DeepanshKhurana commented
@jakubnowicki I believe we should be good here and @vituri already confirmed all the comments were addressed. I believe (2?) sequential branches have already been merged into this by him as well. So, we should avoid bloating this further and merge it. Additionally, I could not push to the main repository anymore (I assumed I would be able to do it but some permission issue prevented it) so I forked and created a !23 to add his suggestion for `check_error_text()` in his comment above. I suggest we merge that after we merge this to `main`.

2026-04-06 18:48 UTC, DeepanshKhurana commented
@jakubnowicki Can we please merge this? I think this is pending a re-review from you still after @vituri's comments and review which confirms all the above items are addressed.

2026-04-24 11:24 UTC, jakubnowicki approved these changes

2026-04-24 11:24 UTC, merged